[cisco_devices]
F1 ansible_host=10.255.12.5
S1 ansible_host=10.255.12.6
S2 ansible_host=10.255.12.102
S3 ansible_host=10.255.13.26
S4 ansible_host=10.255.12.22
E1 ansible_host=10.255.12.13
R1 ansible_host=10.255.12.14
C1 ansible_host=192.168.199.10

[cisco_devices:vars]
ansible_network_os=cisco.ios.ios
ansible_user=admin
ansible_password=C1sc0123
ansible_connection=network_cli
ansible_network_cli_ssh_type=libssh
